### ISSUE TITLE
Always return speed and fuel values as a list.

### ISSUE THREAD

**Issue by gecoombs** [antarctica/PolarRoute#131]
Currently we return speed and fuel as single values for each cell unless we are considering the wind resistance. In this case we return a list of 8 values corresponding to the 8 angular sectors we use to discretise the wind resistance. Moving forwards we want to return them in a consistent way, this means returning a list of 8 equal values instead of a single value when no wind data has been used.

**Comment by SamuelHall700** [comment]
This change with cause some differences in the resultant mesh when running vessel performance, causing parts of our regression testing suite to fail. 

The tests expects to fail in this change are:
`test_regression.py::test_vp_mesh_cellbox_values[.\example_meshes\Vessel_Performance_Meshes\add_vehicle.output2017_6_80.json]`
`test_regression.py::test_vp_mesh_cellbox_values[.\example_meshes\Vessel_Performance_Meshes\add_vehicle.output2019_6_80.json]`
`test_regression.py::test_vp_mesh_cellbox_values[.\example_meshes\Vessel_Performance_Meshes\add_vehicle.output2013_4_80.json]`

If this change results in any other tests failing, it should be investigated further. 

Once the results of the change have been validated, the regression test files will need to be updated to the new format, so the tests pass going forward. The pull request for this update should follow a similar format to https://github.com/antarctica/PolarRoute/pull/129 , including pytests results both before and after the regression test changes have been applied

**Comment by gecoombs** [comment]
After the changes in a72f10e the code now returns a list of 8 floats for speed and fuel with any input data. These changes caused 3 regression tests to fail in an expected way (the list values that were previously floats no longer matched the output in the example meshes):

[pytest_output_code_changes.txt](https://github.com/antarctica/PolarRoute/files/10805363/pytest_output_code_changes.txt)

After updating the values in the example meshes to the new list format 2 of these tests passed but one was still failing with a small number of cells still not identical:

[pytest_output_example_changes.txt](https://github.com/antarctica/PolarRoute/files/10805440/pytest_output_example_changes.txt)

This was determined to be due to rounding errors as while float values were being rounded to 5 decimal places before comparison there was no rounding procedure for lists of float values. After adding this additional rounding step for list values all tests now pass:

[pytest_output_test_changes.txt](https://github.com/antarctica/PolarRoute/files/10805454/pytest_output_test_changes.txt)

**Comment by gecoombs** [comment]
After discussion with @Ulvetanna and some testing it appears that the above issue is already fixed on the branch [path_smoothing_GC](https://github.com/antarctica/PolarRoute/tree/path_smoothing_GC) as the route I tried previously works fine on that branch with the modified mesh format from this branch. The next step is to merge the changes from [path_smoothing_GC](https://github.com/antarctica/PolarRoute/tree/path_smoothing_GC) into [integration_testing](https://github.com/antarctica/PolarRoute/tree/integration_testing) and then update this branch accordingly.

**Comment by gecoombs** [comment]
With the changes I made to the route planner code in 5277e51 we can now plan routes with an input mesh using this list format for speed and fuel. This works for both the dijkstra and the smoothed routes. I'll run the regression tests again and then submit a pull request to merge back into [integration_testing](https://github.com/antarctica/PolarRoute/tree/integration_testing).
