### ISSUE TITLE
PolarRoute - pep8 & Sonar Compliance

### ISSUE THREAD

**Issue by SamuelHall700** [antarctica/PolarRoute#134]
A recent pull request into PolarRoute has highlighted some sections of the codebase which do not conform with pep8 standards. SonarLint (https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio2022) also highlights many sections of the codebase which could be improved. 

Issues are mostly found in files (_though may also be present in others_):
**crossing.py
route_planner.py**

Issues are mostly of the form:

- commented out code present
- variable names not pep8 compliant (_should be of the form ^[_a-z][a-z0-9_]*$._)
- functions names not pep8 compliant (_should be of the form ^[a-z_][a-z0-9_]*$._)
- unused parameters passed to functions
- functions missing docstrings (_crossing.py is missing 10!_)
- many functions have very high cognitive complexity and could be refactored.

**Comment by gecoombs** [comment]
This should be addressed as part of: https://github.com/antarctica/SDADT-project/issues/109

**Comment by Ulvetanna** [comment]
@SamuelHall700 stated this has been completed
