### ISSUE TITLE
Comments from running PolarRoute on visual_ice SIC layers

### ISSUE THREAD

**Issue by MartinSJRogers** [antarctica/PolarRoute#219]
I have now run PolarRoute on 5 - 6 different SIC layers derived from visual_ice. I supply below some considerations for future PolarRoute modifications when working with higher resolution data:

- Apply a buffer to cells with high SIC. For example it would not be ideal to skirt around icebergs (Figure 1). 
- Smooth the route- it is undesirable and impractical for the ship to change direction every 250 m, so a penalty for changing direction is required (Figure 2).
- I do not think the penalty for travelling through a grid cell with high SIC is great enough. In Figure 3 I would expect the route to go through one of the two areas in orange, compared to the route derived by PolarRoute in red. 

I have generated routes using the scripts Sam shared on 6th July- happy to share again here is necessary. Note for this exercise I used a vessel config with MaxIceConc = 95%. This was to allow routes to go through areas where a low number of grid cells had a high SIC. 

All comments are non-urgent, and great to see the software working on higher res imagery :) 

Figure 1: Buffer required to prevent route from skirting around icebergs and other areas of high SIC.
![image](https://github.com/antarctica/PolarRoute/assets/43956226/8f2e7209-fcff-4eca-873f-1eb52a793ddd)

Figure 2: Risk of too many directional changes.
![image](https://github.com/antarctica/PolarRoute/assets/43956226/f3d8d697-ae9b-4512-980f-236960360c0a)

Figure 3: Route derived by PolarRoute (red) compared to the ones I would expect drawn freehand in orange.
![image](https://github.com/antarctica/PolarRoute/assets/43956226/3977e35d-8e5a-4b49-9284-3e0efc636fd6)

**Comment by Ulvetanna** [comment]
It's nice to start seeing PolarRoute used at a higher resolution ! :) 

Currently the time and fuel usage of the ship in different sea-ice concentrations is based on vessel performance characteristics provided by the carbon accounting team. As the relationship is non-linear, in some cases it's more temporal/fuel efficient to actually do icebreaking than navigate longer distances. I think that is what could be the case for your second figure. Using the `calculate_route` function should allow you to inspect your manually chosen routes to see the difference from the optimised. In addition, you can plot the ship fuel and speed maps to really dive into the how the SIC is effecting the efficiency.

Currently you're still looking at grid-based routes, the inclusion of physics based path-smoothing will also help improve the routes. After lots of bug fixing these corrections should be included into 0.2.x release in the next couple of days :) 

As an aside, in the long-run we are hoping that PolarRoute acts as the long-distance route planning toolkit, whilst the higher resolution in-ice navigation would be using a risk-based routing system. Ayat is currently working on a Gaussian-process risk aware routing that takes an environmental temporal risk map (in the long run this will be the probability of temporal sea-ice change multiple by severity) so we can leverage your images as a time series in this problem as well :) Looking forward to working with you more on this going forward :)

**Comment by gecoombs** [comment]
Hi @MartinSJRogers, just to let you know we've now released the new v0.2 of PolarRoute. So if you merge `main` into your branch you should be able to try out some of the new features we mentioned above 🙂

**Comment by gecoombs** [comment]
The dataloader for visual_ice is now available for use with the latest code as part of MeshiPhi: https://github.com/antarctica/MeshiPhi/tree/visual_ice. I'll close this issue for now as there has been no discussion for ~6 months.
