### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by Ulvetanna** [antarctica/PolarRoute#248]
***Description***
The documentation currently still needs a lot of work. 

The `Examples of running code` example in the repo is un-populated. All un-populated pages should be removed. Once we have finalised we can give to member of the group not working on this aspect of the project to check if they can get an example running without help.

As most people looking at the software will only spend 1-2 mins to try and get it working this means that the welcome page should show a very simple example. I would suggest a link to recreate a full route-planning example using Colab (Then they shouldn't need to install the Python Package. 
In addition, all your example meshes in the Github codebase are not visible for people on PyPI so we need to include these examples on a shared drive (one drive), so that the user can install and run the example directly from Docs and PyPI without having to install Github Repo.

There is currently issues for @foxm1 for building the software from sphinx with the differences between the built manual showing empty Vessel Performance doc-strings relative to the Github IO Manual

**Comment by gecoombs** [comment]
Empty sections of the docs have been removed and the text has been updated to reflect all recent changes to the code. Issues with examples and installation instructions have been addressed as part of #249 and #250.
