### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by Ulvetanna** [antarctica/PolarRoute#249]
Installation documentation is very complicated for those who haven't been working on the project. This process should be streamlined so new members can install the codebase with ease. Make the assumption that someone will only try once and if that fails will give up on the codebase.

Some of the main issues to be addressed:
- [ ] Documentation is very unclear for installation using `venv`. Although this is one virtual environment you should have another section using `conda installation`. The conda installation should be a single line `conda create -n PolarRoute polar-route` but this does not work due to the next issue
- [x] PyPI version of PolarRoute is inconsistent. 
- [ ] PolarRoute doesn't install clean with MeshiPhi from the Github Repo using 'python setup.py install' and requires a separate PyPI of MeshiPhi.

**Comment by gecoombs** [comment]
Installation instructions have been updated and simplified. Mention of `venv` has been removed and the simplest way to install PolarRoute (from PyPI with pip) is presented first. Installation from a local copy of the source code is now done using pip as using `python setup.py install` is deprecated and was no longer working when installing into a fresh python environment.
