### ISSUE TITLE
Bug -  PolarRoute last leg of path

### ISSUE THREAD

**Issue by Ulvetanna** [antarctica/PolarRoute#253]
@Ulvetanna found an example of this for the Glider routing toy example. Go back to this example and check out the issue and post it as a bug that can be fixed and investigated by others

**Comment by SamuelHall700** [comment]
@Ulvetanna any updates on this one? An example of this bug has still not been provided for further investigation.

**Comment by Ulvetanna** [comment]
@SamuelHall700 think this is worth reconsidering once the path construction unit tests are complete. As such closing until a later date and will pickup on a separate issue
