### ISSUE TITLE
Splitting around waypoint for route planning

### ISSUE THREAD

**Issue by Ulvetanna** [antarctica/PolarRoute#275]
Waypoints residing in large cells is leading to discrepancies in the routes. In order to address this issue we can leverage the MeshiPhi functionality of `.split_points` to split around a series of lat.long waypoints; this will then split down to the maximum split depth. This functionality should be optional and should be added also into the config.

**Comment by SamuelHall700** [comment]
Pull request for this issue is in, but tests are currently failing due to a pre-exsisting issue

**Comment by Ulvetanna** [comment]
@SamuelHall700 updating the tests in the pull request to allow for changes in the path smoothing. Will also add in additional regression tests to include the new splitting around waypoints.

**Comment by Ulvetanna** [comment]
This has been merged into the 0.5.x branch
