### ISSUE TITLE
doc/build/sections/Examples.html run through needs refinement

### ISSUE THREAD

**Issue by JimCircadian** [antarctica/PolarRoute#67]
The run through needs some refinement, in that the notebook probably doesn't need to be in the repo and the data needs to be redistributed correctly (not via google drive)

* [ ] Relative directory (instructions, if not using notebook, need to be run from Examples/)
* [ ] jupyter-notebook isn't in the install instructions for the library (assumed dependency)
* [ ] BSOSE and SOSE datafiles aren't available (I have them to hand)

These steps are required for the in-built example (open to discussion)
* [ ] Create script to download the data assets required and make a script version of this which can be entry pointed as a demo
* [ ]

**Comment by gecoombs** [comment]
Given the general changes made since August and the fact that all jupyter notebooks have been removed from the repo should we just close this issue? Possibly worth creating a new, more up to date, one around automated running of examples? @SamuelHall700
