### ISSUE TITLE
Mesh - Mesh generation optimisation

### ISSUE THREAD

**Issue by JimCircadian** [antarctica/PolarRoute#86]
**Feature Request**

Mesh generation will be well served by some overhaul in the following areas:

* [ ] Reviewing the pythonic implementation of data structures and their use
* [ ] Reviewing the efficiency and structure of data flowing out of data_loaders into the mesh
* [ ] Reviewing the memory footprints of the data flowing around (see #68 for reasons why this is important)
* [ ] Enabling the use of distributed compute via `xarray` and `dask`, which offer equivalent functionality to `pandas` and `numpy` but with geospatial and distribution concerns taken care of (in fact, they leverage these under the hood)

**Describe the solution you'd like**

A subclassed implementation that abstracts the old from the interface, and offers a new implementation as an alternative that can be easily subclassed.

Consider the implementation of abstract base classes `BaseMesh` and `BaseCellBox` with well defined interfaces. Then shift the existing implementation to a child and also create the new distributed versions. These can then be instantiated via configurations. We might also want to create a `JavaMesh` child implementation instead of using feature flags.

**Describe alternatives you've considered**

I've considered not adding this, but this code needs restructuring to allow various meshing implementations (there are already two distinct implementations within one class.) Over time this will need refactoring, and it's better done now than later.

**Comment by Ulvetanna** [comment]
I have now moved this issue from `enhancement` to `issues` as it is now becoming more pressing for the creation of larger environmental meshes. This issue has been assigned to @SamuelHall700 or a member of his entourage

**Comment by Ulvetanna** [comment]
This is being addressed in the mesh re-architecture.
